# Generated by Django 2.0.1 on 2018-04-12 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repo',
            name='type',
            field=models.CharField(default='object', max_length=255),
        ),
    ]
